version: '3.9'
services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pizza-menu
    env_file:
      - .env
    environment:
      DOCKER_POSTGRES_URL: jdbc:postgresql://${DATABASE_CONTAINER_NAME}:${DATABASE_CONTAINER_PORT}/${DATABASE_NAME}
    ports:
      - "${SERVICE_PORT}:8082"
    networks:
      - pizza_network

networks:
  pizza_network:
    external: true
