server:
  port: 8092


auth:
  grpc:
    host: ${AUTH_CONTAINER_NAME}
    port: ${GRPC_AUTH_PORT}

spring:
  application:
    name: pizza-menu
  datasource:
    url: ${DOCKER_POSTGRES_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}




