server:
    port: ${AUTH_INTERNAL_PORT}

spring:
    grpc:
        server:
            port: ${GRPC_AUTH_SERVER_PORT}
    security:
        jwt:
            secret: ${JWT_SECRET}
            access: 1
            refresh: 30
    mail:
        host: ${SPRING_MAIL_HOST}
        port: ${SPRING_MAIL_PORT}
        username: ${SPRING_MAIL_USERNAME}
        password: ${SPRING_MAIL_PASSWORD}
        properties:
            mail:
                debug: false
                transport:
                    protocol: smtp
                smtp:
                    auth: true
                    starttls:
                        enable: true
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}

management:
    endpoint:
        health:
            enabled: true
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info