server:
  port: ${GATEWAY_INTERNAL_PORT}
  forward-headers-strategy: framework

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: pizza-auth
          uri: ${AUTH_URL}
          predicates:
            - Path=/auth/**,/users/**
            - Method=GET,POST, PATCH
        - id: pizza-menu
          uri: ${MENU_URL}
          predicates:
            - Path=/menu/**,/cart/**
            - Method=GET,POST, PATCH


logging:
  level:
    org.springframework.cloud.gateway: TRACE