server:
  port: 8880
  forward-headers-strategy: framework


spring:
  application:
    name: pizza-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: pizza-auth
          uri: ${DOCKER_AUTH_URL}
          predicates:
            - Path=/auth/**,/users/**
            - Method=GET,POST, PATCH
        - id: pizza-menu
          uri: ${DOCKER_MENU_URL}
          predicates:
            - Path=/menu/**,/cart/**
            - Method=GET,POST, PATCH


logging:
  level:
    org.springframework.cloud.gateway: TRACE