version: '3.9'
services:
  postgres:
    container_name: pizza-database
    image: postgres:12
    hostname: pizza
    env_file:
      - .env
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${SERVICE_PORT}:5432"
    networks:
      - pizza_network
  flyway:
    image: flyway/flyway
    container_name: pizza-flyway
    command:
      - migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${PG_DATABASE}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 5
    volumes:
      - ./database/migrations:/flyway/sql
    depends_on:
      - postgres
    networks:
      - pizza_network

networks:
  pizza_network:
    external: true
